server:
  port: 5001
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/szs
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none



jwt:
  secretKey : D9A20C953DFA9A25AF71539A627DEDB5ED2997EAF1294C0F9A6351036EC9A351

external:
  thirdPartyUrl: https://codetest.3o3.co.kr

